import { Services } from "../types/services.type";

export const servicesList: Services[] = [
  {
    id: 0,
    image: "/warsztat_pieknych_wlosow/img/services/HairSkinPeeling.svg",
    name: "Peeling skóry włosów",
    category: "Podstawowe usługi fryzjera",
    options: ["Krótkie włosy", "Do ramion", "Do łopatki", "Do pasa"],
    cost: [80, 100, 120, 150],
  },
  {
    id: 1,
    image: "/warsztat_pieknych_wlosow/img/services/HairLamination.svg",
    name: "Laminowanie włosów",
    category: "Podstawowe usługi fryzjera",
    options: ["Do ramion", "Do łopatki", "Do pasa"],
    cost: [150, 200, 250],
  },
  {
    id: 2,
    image: "/warsztat_pieknych_wlosow/img/services/UrgentHairRestoration.svg",
    name: "Odbudowa włosów SOS",
    category: "Podstawowe usługi fryzjera",
    options: ["Do ramion", "Do łopatki", "Do pasa"],
    cost: [100, 150, 200],
  },
  {
    id: 3,
    image: "/warsztat_pieknych_wlosow/img/services/ManHaircut.svg",
    name: "Strzyżenie męskie",
    category: "Podstawowe usługi fryzjera",
    options: ["Bez mycia", "Mycie, stylizacja", "Oczyszcznie skóry, mycie, stylizacja"],
    cost: [50, 70, 100],
  },
  {
    id: 4,
    image: "/warsztat_pieknych_wlosow/img/services/BangsCut.svg",
    name: "Obcinanie grzywki",
    category: "Podstawowe usługi fryzjera",
    options: [],
    cost: 20,
  },
  {
    id: 5,
    image: "/warsztat_pieknych_wlosow/img/services/ChildHaircut.svg",
    name: "Strzyżenie dzieci do 7 lat",
    category: "Podstawowe usługi fryzjera",
    options: [],
    cost: 60,
  },
  {
    id: 6,
    image: "/warsztat_pieknych_wlosow/img/services/WomanHaircut.svg",
    name: "Strzyżenie damskie",
    category: "Podstawowe usługi fryzjera",
    options: ["Krótkie-średnie", "Średnie-długie"],
    cost: [120, 140],
  },
  {
    id: 7,
    image: "/warsztat_pieknych_wlosow/img/services/EndsTrimming.svg",
    name: "Podcinanie końcówek maszynką",
    category: "Podstawowe usługi fryzjera",
    options: ["Bez mycia", "Z myciem"],
    cost: [50, 100],
  },
  {
    id: 8,
    image: "/warsztat_pieknych_wlosow/img/services/HairModeling.svg",
    name: "Modelowanie włosów",
    category: "Podstawowe usługi fryzjera",
    options: [],
    cost: 80,
  },
  {
    id: 9,
    image: "/warsztat_pieknych_wlosow/img/services/HairColoring.svg",
    name: "Farbowanie włosów (Pasemka, Balojaż)",
    category: "Podstawowe usługi fryzjera",
    options: [],
    cost: 350,
  },
  {
    id: 10,
    image: "/warsztat_pieknych_wlosow/img/services/RegrowthColoring.svg",
    name: "Farbowanie odrostów (Pasemka, Balojaż)",
    category: "Podstawowe usługi fryzjera",
    options: [],
    cost: 250,
  },
  {
    id: 11,
    image: "/warsztat_pieknych_wlosow/img/services/AirtouchColoring.svg",
    name: "Farbowanie AirTouch",
    category: "Podstawowe usługi fryzjera",
    options: ["Do ramion", "Do łopatki", "Do pasa"],
    cost: [500, 700, 800],
  },
  {
    id: 12,
    image: "/warsztat_pieknych_wlosow/img/services/ColorfulBath.svg",
    name: "Kolorowa kąpiel",
    category: "Podstawowe usługi fryzjera",
    options: ["Neutralizacja żółtego", "Nadanie niuansowi kolor"],
    cost: [150, 200],
  },
  {
    id: 13,
    image: "/warsztat_pieknych_wlosow/img/services/Toning.svg",
    name: "Tonowanie ton w ton i ciemniejszy",
    category: "Podstawowe usługi fryzjera",
    options: ["Do ramion", "Do łopatki", "Do pasa"],
    cost: [150, 200, 250],
  },
  {
    id: 14,
    image: "/warsztat_pieknych_wlosow/img/services/Consulting.svg",
    name: "Konsultacja fryzjera",
    category: "Podstawowe usługi fryzjera",
    options: [],
    cost: 0,
  },
  {
    id: 15,
    image: "/warsztat_pieknych_wlosow/img/services/RegrowthColoringDark.svg",
    name: "Farbowanie odrostów ciemny",
    category: "Podstawowe usługi fryzjera",
    options: ["Krótkie", "Średnie", "Długie"],
    cost: [200, 250, 300],
  },
  {
    id: 16,
    image: "/warsztat_pieknych_wlosow/img/services/RegrowthColoringBlond.svg",
    name: "Farbowanie odrostów blond",
    category: "Podstawowe usługi fryzjera",
    options: ["Krótkie", "Średnie", "Długie"],
    cost: [300, 350, 400],
  },
  {
    id: 17,
    image: "/warsztat_pieknych_wlosow/img/services/CientDyeColoring.svg",
    name: "Farbowanie włosów farbą klienta",
    category: "Podstawowe usługi fryzjera",
    options: ["Krótkie", "Średnie", "Długie"],
    cost: [120, 130, 150],
  },
  {
    id: 18,
    image: "/warsztat_pieknych_wlosow/img/services/BIOHairCurling.svg",
    name: "Kręcenie włosów BIO",
    category: "Trwałe usługi fryzjera",
    options: ["Do ramion", "Do łopatki", "Do pasa"],
    cost: [250, 350, 450],
  },
  {
    id: 19,
    image: "/warsztat_pieknych_wlosow/img/services/BIOHairCurlingMan.svg",
    name: "Męskie kręcenie włosów BIO",
    category: "Trwałe usługi fryzjera",
    options: [],
    cost: 150,
  },
  {
    id: 20,
    image: "/warsztat_pieknych_wlosow/img/services/RootVolume.svg",
    name: "Objętość korzenia",
    category: "Trwałe usługi fryzjera",
    options: ["Krótkie włosy", "Do ramion", "Do łopatki", "Do pasa"],
    cost: [100, 150, 200, 250],
  },
  {
    id: 21,
    image: "/warsztat_pieknych_wlosow/img/services/ManicureHybrid.svg",
    name: "Manicure hybrydowy",
    category: "Usługi manicure",
    options: ["Zwykły", "French"],
    cost: [150, 160],
  },
  {
    id: 22,
    image: "/warsztat_pieknych_wlosow/img/services/Manicure.svg",
    name: "Manicure",
    category: "Usługi manicure",
    options: ["Złykły lakier", "Bez malowania", "Z odżywką"],
    cost: [80, 70, 75],
  },
  {
    id: 23,
    image: "/warsztat_pieknych_wlosow/img/services/NailsFixing.svg",
    name: "Naprawa paznokcia",
    category: "Usługi manicure",
    options: [],
    cost: 10,
  },
  {
    id: 24,
    image: "/warsztat_pieknych_wlosow/img/services/Massage.svg",
    name: "Masaż dłoni",
    category: "Usługi manicure",
    options: [],
    cost: 10,
  },
  {
    id: 25,
    image: "/warsztat_pieknych_wlosow/img/services/AdditionNailsStr.svg",
    name: "Dodatkowe wzmocnienie paznokcia",
    category: "Usługi manicure",
    options: [],
    cost: 2,
  },
  {
    id: 26,
    image: "/warsztat_pieknych_wlosow/img/services/ExpressManicure.svg",
    name: "Express Manicure",
    category: "Usługi manicure",
    options: [],
    cost: 100,
  },
  {
    id: 27,
    image: "/warsztat_pieknych_wlosow/img/services/Pedicure.svg",
    name: "Pedicure",
    category: "Pedicure",
    options: ["Tylko pięty", "Tylko palce", "Bez malowania", "Zwykły lakier", "Hybrydowy"],
    cost: [50, 90, 100, 120, 180],
  },
  {
    id: 28,
    image: "/warsztat_pieknych_wlosow/img/services/PedicureManicure.svg",
    name: "Pedicure + manicure",
    category: "Pedicure",
    options: [],
    cost: 300,
  },
  {
    id: 29,
    image: "/warsztat_pieknych_wlosow/img/services/LightTherapy.svg",
    name: "Światłoterapia",
    category: "Terapia światłem oraz fotoodmładzanie",
    options: ["10 minut", "100 minut"],
    cost: [30, 200],
  },
  {
    id: 30,
    image: "/warsztat_pieknych_wlosow/img/services/Photorejuvenation.svg",
    name: "Fotoodmładzanie",
    category: "Terapia światłem oraz fotoodmładzanie",
    options: ["1 zabieg", "5 zabieg"],
    cost: [90, 360],
  },
];
