import { getImageUrl } from '../helpers/helpers';
import { Services } from '../types/services.type';
import { Request } from 'express';

export const servicesList = (req: Request): Services[] => [
  {
    _id: 0,
    image: getImageUrl(req, 'images/services/HairSkinPeeling.svg'),
    name: 'Peeling skóry włosów',
    category: 'Podstawowe usługi fryzjera',
    last: 2,
    masters: ['Natalia'],
    options: ['Krótkie włosy', 'Do ramion', 'Do łopatki', 'Do pasa'],
    cost: [80, 100, 120, 150],
  },
  {
    _id: 1,
    image: getImageUrl(req, 'images/services/HairLamination.svg'),
    name: 'Laminowanie włosów',
    category: 'Podstawowe usługi fryzjera',
    options: ['Do ramion', 'Do łopatki', 'Do pasa'],
    masters: ['Natalia'],
    last: 3,
    cost: [150, 200, 250],
  },
  {
    _id: 2,
    image: getImageUrl(req, 'images/services/UrgentHairRestoration.svg'),
    name: 'Odbudowa włosów SOS',
    category: 'Podstawowe usługi fryzjera',
    masters: ['Natalia'],
    last: 4,
    options: ['Do ramion', 'Do łopatki', 'Do pasa'],
    cost: [100, 150, 200],
  },
  {
    _id: 3,
    image: getImageUrl(req, 'images/services/ManHaircut.svg'),
    name: 'Strzyżenie męskie',
    category: 'Podstawowe usługi fryzjera',
    masters: ['Natalia'],
    last: 2,
    options: ['Bez mycia', 'Mycie, stylizacja', 'Oczyszcznie skóry, mycie, stylizacja'],
    cost: [50, 70, 100],
  },
  {
    _id: 4,
    image: getImageUrl(req, 'images/services/BangsCut.svg'),
    name: 'Obcinanie grzywki',
    category: 'Podstawowe usługi fryzjera',
    masters: ['Natalia'],
    last: 1,
    options: [],
    cost: 20,
  },
  {
    _id: 5,
    image: getImageUrl(req, 'images/services/ChildHaircut.svg'),
    name: 'Strzyżenie dzieci do 7 lat',
    category: 'Podstawowe usługi fryzjera',
    masters: ['Natalia'],
    last: 2,
    options: [],
    cost: 60,
  },
  {
    _id: 6,
    image: getImageUrl(req, 'images/services/WomanHaircut.svg'),
    name: 'Strzyżenie damskie',
    category: 'Podstawowe usługi fryzjera',
    masters: ['Natalia'],
    last: 4,
    options: ['Krótkie-średnie', 'Średnie-długie'],
    cost: [120, 140],
  },
  {
    _id: 7,
    image: getImageUrl(req, 'images/services/EndsTrimming.svg'),
    name: 'Podcinanie końcówek maszynką',
    category: 'Podstawowe usługi fryzjera',
    masters: ['Natalia'],
    last: 1,
    options: ['Bez mycia', 'Z myciem'],
    cost: [50, 100],
  },
  {
    _id: 8,
    image: getImageUrl(req, 'images/services/HairModeling.svg'),
    name: 'Modelowanie włosów',
    category: 'Podstawowe usługi fryzjera',
    masters: ['Natalia'],
    last: 6,
    options: [],
    cost: 80,
  },
  {
    _id: 9,
    image: getImageUrl(req, 'images/services/HairColoring.svg'),
    name: 'Farbowanie włosów (Pasemka, Balojaż)',
    category: 'Podstawowe usługi fryzjera',
    masters: ['Natalia'],
    last: 6,
    options: [],
    cost: 350,
  },
  {
    _id: 10,
    image: getImageUrl(req, 'images/services/RegrowthColoring.svg'),
    name: 'Farbowanie odrostów (Pasemka, Balojaż)',
    category: 'Podstawowe usługi fryzjera',
    masters: ['Natalia'],
    last: 2,
    options: [],
    cost: 250,
  },
  {
    _id: 11,
    image: getImageUrl(req, 'images/services/AirtouchColoring.svg'),
    name: 'Farbowanie AirTouch',
    category: 'Podstawowe usługi fryzjera',
    masters: ['Natalia'],
    last: 5,
    options: ['Do ramion', 'Do łopatki', 'Do pasa'],
    cost: [500, 700, 800],
  },
  {
    _id: 12,
    image: getImageUrl(req, 'images/services/ColorfulBath.svg'),
    name: 'Kolorowa kąpiel',
    category: 'Podstawowe usługi fryzjera',
    masters: ['Natalia'],
    last: 4,
    options: ['Neutralizacja żółtego', 'Nadanie niuansowi kolor'],
    cost: [150, 200],
  },
  {
    _id: 13,
    image: getImageUrl(req, 'images/services/Toning.svg'),
    name: 'Tonowanie ton w ton i ciemniejszy',
    masters: ['Natalia'],
    last: 6,
    category: 'Podstawowe usługi fryzjera',
    options: ['Do ramion', 'Do łopatki', 'Do pasa'],
    cost: [150, 200, 250],
  },
  {
    _id: 14,
    image: getImageUrl(req, 'images/services/Consulting.svg'),
    name: 'Konsultacja fryzjera',
    masters: ['Natalia'],
    last: 0,
    category: 'Podstawowe usługi fryzjera',
    options: [],
    cost: 0,
  },
  {
    _id: 15,
    image: getImageUrl(req, 'images/services/RegrowthColoringDark.svg'),
    name: 'Farbowanie odrostów ciemny',
    category: 'Podstawowe usługi fryzjera',
    masters: ['Natalia'],
    last: 4,
    options: ['Krótkie', 'Średnie', 'Długie'],
    cost: [200, 250, 300],
  },
  {
    _id: 16,
    image: getImageUrl(req, 'images/services/RegrowthColoringBlond.svg'),
    name: 'Farbowanie odrostów blond',
    category: 'Podstawowe usługi fryzjera',
    masters: ['Natalia'],
    last: 5,
    options: ['Krótkie', 'Średnie', 'Długie'],
    cost: [300, 350, 400],
  },
  {
    _id: 17,
    image: getImageUrl(req, 'images/services/CientDyeColoring.svg'),
    name: 'Farbowanie włosów farbą klienta',
    category: 'Podstawowe usługi fryzjera',
    masters: ['Natalia'],
    last: 4,
    options: ['Krótkie', 'Średnie', 'Długie'],
    cost: [120, 130, 150],
  },
  {
    _id: 18,
    image: getImageUrl(req, 'images/services/BIOHairCurling.svg'),
    name: 'Kręcenie włosów BIO',
    category: 'Trwałe usługi fryzjera',
    masters: ['Natalia'],
    last: 8,
    options: ['Do ramion', 'Do łopatki', 'Do pasa'],
    cost: [250, 350, 450],
  },
  {
    _id: 19,
    image: getImageUrl(req, 'images/services/BIOHairCurlingMan.svg'),
    name: 'Męskie kręcenie włosów BIO',
    category: 'Trwałe usługi fryzjera',
    masters: ['Natalia'],
    last: 8,
    options: [],
    cost: 150,
  },
  {
    _id: 20,
    image: getImageUrl(req, 'images/services/RootVolume.svg'),
    name: 'Objętość korzenia',
    category: 'Trwałe usługi fryzjera',
    masters: ['Natalia'],
    last: 4,
    options: ['Krótkie włosy', 'Do ramion', 'Do łopatki', 'Do pasa'],
    cost: [100, 150, 200, 250],
  },
  {
    _id: 21,
    image: getImageUrl(req, 'images/services/_ManicureHybrid.svg'),
    name: 'Manicure hybrydowy',
    category: 'Usługi manicure',
    masters: ['Waleria'],
    last: 6,
    options: ['Zwykły', 'French'],
    cost: [150, 160],
  },
  {
    _id: 22,
    image: getImageUrl(req, 'images/services/Manicure.svg'),
    name: 'Manicure',
    category: 'Usługi manicure',
    masters: ['Waleria'],
    last: 4,
    options: ['Złykły lakier', 'Bez malowania', 'Z odżywką'],
    cost: [80, 70, 75],
  },
  {
    _id: 23,
    image: getImageUrl(req, 'images/services/NailsFixing.svg'),
    name: 'Naprawa paznokcia',
    category: 'Usługi manicure',
    masters: ['Waleria'],
    last: 1,
    options: [],
    cost: 10,
  },
  {
    _id: 24,
    image: getImageUrl(req, 'images/services/Massage.svg'),
    name: 'Masaż dłoni',
    category: 'Usługi manicure',
    masters: ['Waleria'],
    last: 1,
    options: [],
    cost: 10,
  },
  {
    _id: 25,
    image: getImageUrl(req, 'images/services/AdditionNailsStr.svg'),
    name: 'Dodatkowe wzmocnienie paznokcia',
    category: 'Usługi manicure',
    masters: ['Waleria'],
    last: 1,
    options: [],
    cost: 2,
  },
  {
    _id: 26,
    image: getImageUrl(req, 'images/services/ExpressManicure.svg'),
    name: 'Express Manicure',
    category: 'Usługi manicure',
    masters: ['Waleria'],
    last: 2,
    options: [],
    cost: 100,
  },
  {
    _id: 27,
    image: getImageUrl(req, 'images/services/Pedicure.svg'),
    name: 'Pedicure',
    category: 'Pedicure',
    masters: ['Waleria'],
    last: 4,
    options: ['Tylko pięty', 'Tylko palce', 'Bez malowania', 'Zwykły lakier', 'Hybrydowy'],
    cost: [50, 90, 100, 120, 180],
  },
  {
    _id: 28,
    image: getImageUrl(req, 'images/services/PedicureManicure.svg'),
    name: 'Pedicure + manicure',
    category: 'Pedicure',
    masters: ['Waleria'],
    last: 8,
    options: [],
    cost: 300,
  },
  {
    _id: 29,
    image: getImageUrl(req, 'images/services/LightTherapy.svg'),
    name: 'Światłoterapia',
    category: 'Terapia światłem oraz fotoodmładzanie',
    masters: ['Waleria'],
    last: 1,
    options: ['10 minut', '100 minut'],
    cost: [30, 200],
  },
  {
    _id: 30,
    image: getImageUrl(req, 'images/services/Photorejuvenation.svg'),
    name: 'Fotoodmładzanie',
    category: 'Terapia światłem oraz fotoodmładzanie',
    masters: ['Waleria'],
    last: 1,
    options: ['1 zabieg', '5 zabiegów'],
    cost: [90, 360],
  },
];
